table D_Type
	lineageTag: efe9a121-5e33-482b-bc27-2f76da287856

	column id
		dataType: int64
		formatString: 0
		lineageTag: 3683d8a6-9b9b-46ed-abaa-83465d5a52b6
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column level_2_label
		dataType: string
		lineageTag: bb45f69f-e9c6-407c-adbc-df2be9fddd0e
		summarizeBy: none
		sourceColumn: level_2_label

		annotation SummarizationSetBy = Automatic

	column level_3_label
		dataType: string
		lineageTag: cb0786ec-952d-454c-8d24-4d25826082c4
		summarizeBy: none
		sourceColumn: level_3_label

		annotation SummarizationSetBy = Automatic

	column level_4_label
		dataType: string
		lineageTag: b670b310-f33b-462b-9e81-da792e8217c5
		summarizeBy: none
		sourceColumn: level_4_label

		annotation SummarizationSetBy = Automatic

	column level_1_id
		dataType: int64
		formatString: 0
		lineageTag: afb36f81-d563-462e-838a-9f9595ff89d7
		summarizeBy: none
		sourceColumn: level_1_id

		annotation SummarizationSetBy = Automatic

	column level_1_label
		dataType: string
		lineageTag: 7653c28d-ecf9-4b58-b2c8-23cb791c8134
		summarizeBy: none
		sourceColumn: level_1_label

		annotation SummarizationSetBy = Automatic

	column type_url
		dataType: string
		lineageTag: 41ca67a1-7af5-461c-b756-fe8d70b1ebaa
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: type_url

		annotation SummarizationSetBy = Automatic

	partition D_Type = m
		mode: import
		queryGroup: DIMs
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\jirip\Documents\Developer\python\kriminalita\dimensions\D_type.csv"),[Delimiter=",", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"level_1_id", Int64.Type}, {"level_1_label", type text}, {"level_1_name", type text}, {"level_2_id", Int64.Type}, {"level_2_label", type text}, {"level_2_name", type text}, {"level_3_id", Int64.Type}, {"level_3_label", type text}, {"level_3_name", type text}, {"level_4_id", Int64.Type}, {"level_4_label", type text}, {"level_4_name", type text}, {"name", type text}, {"label", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{ "level_2_id", "level_3_id", "level_4_id", "level_1_name", "level_2_name", "level_3_name", "level_4_name", "name", "label"}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Removed Columns",{{"level_1_label", Text.Proper, type text}}),
				    #"Merged Queries" = Table.NestedJoin(#"Capitalized Each Word", {"level_1_id"}, H_type_url, {"type_key"}, "H_type_url", JoinKind.LeftOuter),
				    #"Expanded H_type_url" = Table.ExpandTableColumn(#"Merged Queries", "H_type_url", {"type_url"}, {"type_url"})
				in
				    #"Expanded H_type_url"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation TabularEditor_TableGroup = DIMs

